CONFIG_ZMK_RGB_UNDERGLOW=y

# Uncomment the following line to increase the keyboard's wireless range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable deep sleep support (default n)
CONFIG_ZMK_SLEEP=y
# Go to deep sleep after an hour
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10
